// <auto-generated />
using System;
using FirstApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstApi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220602123315_AddData2")]
    partial class AddData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstApi.Model.SocialPlatforms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SocialPlatforms");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 6, 2, 14, 33, 15, 565, DateTimeKind.Local).AddTicks(1579),
                            Key = "Twitter",
                            Name = "Twitter"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 6, 2, 14, 33, 15, 565, DateTimeKind.Local).AddTicks(8342),
                            Key = "Instagram",
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2022, 6, 2, 14, 33, 15, 565, DateTimeKind.Local).AddTicks(8352),
                            Key = "Tiktok",
                            Name = "Tiktok"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
