// <auto-generated />
using System;
using FirstApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstApi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220605105345_NewUpdates")]
    partial class NewUpdates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstApi.Model.Languages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("FirstApi.Model.SocialPlatformTranslations", b =>
                {
                    b.Property<int>("SocialPlatformKey")
                        .HasColumnType("int");

                    b.Property<int>("LanguageKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialPlatformKey", "LanguageKey");

                    b.HasIndex("LanguageKey");

                    b.ToTable("SocialPlatformTranslations");
                });

            modelBuilder.Entity("FirstApi.Model.SocialPlatforms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SocialPlatforms");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 6, 5, 12, 53, 45, 153, DateTimeKind.Local).AddTicks(7344),
                            Key = "Twitter"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 6, 5, 12, 53, 45, 154, DateTimeKind.Local).AddTicks(4374),
                            Key = "Instagram"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2022, 6, 5, 12, 53, 45, 154, DateTimeKind.Local).AddTicks(4386),
                            Key = "Tiktok"
                        });
                });

            modelBuilder.Entity("FirstApi.Model.SocialPlatformTranslations", b =>
                {
                    b.HasOne("FirstApi.Model.Languages", "language")
                        .WithMany("SocialPlatformTranslation")
                        .HasForeignKey("LanguageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstApi.Model.SocialPlatforms", "SocialPlatform")
                        .WithMany("SocialPlatformTranslation")
                        .HasForeignKey("SocialPlatformKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("language");

                    b.Navigation("SocialPlatform");
                });

            modelBuilder.Entity("FirstApi.Model.Languages", b =>
                {
                    b.Navigation("SocialPlatformTranslation");
                });

            modelBuilder.Entity("FirstApi.Model.SocialPlatforms", b =>
                {
                    b.Navigation("SocialPlatformTranslation");
                });
#pragma warning restore 612, 618
        }
    }
}
